/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'manufacturer' : IDL.Null,
  'vendor' : IDL.Null,
});
export const BusinessProfile = IDL.Record({
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'businessName' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const ProductCategory = IDL.Variant({
  'closure20Inch' : IDL.Null,
  'closure16Inch' : IDL.Null,
  'bundle12Inch' : IDL.Null,
  'curlyWig' : IDL.Null,
  'closure18Inch' : IDL.Null,
  'bundle14Inch' : IDL.Null,
  'bobWig' : IDL.Null,
  'bundle20Inch' : IDL.Null,
  'bundle16Inch' : IDL.Null,
  'closureWig' : IDL.Null,
  'bundle18Inch' : IDL.Null,
  'supplyBundle' : IDL.Null,
  'frontalWig' : IDL.Null,
  'blondeWig' : IDL.Null,
  'bodyWave' : IDL.Null,
  'closure12Inch' : IDL.Null,
  'deepWave' : IDL.Null,
  'closure14Inch' : IDL.Null,
  'boneStraight' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'moq' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'lastUpdated' : IDL.Int,
  'priceFromCents' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'lengthOptions' : IDL.Vec(IDL.Text),
  'manufacturerId' : IDL.Principal,
  'category' : ProductCategory,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'createdAt' : IDL.Int,
  'totalCents' : IDL.Nat,
  'productId' : IDL.Nat,
  'buyerId' : IDL.Principal,
  'quantity' : IDL.Nat,
  'sellerId' : IDL.Principal,
});
export const ProductMessage = IDL.Record({
  'text' : IDL.Text,
  'productId' : IDL.Nat,
  'receiverId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'senderId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'completeOrder' : IDL.Func([IDL.Nat], [], []),
  'createBusinessProfile' : IDL.Func([BusinessProfile], [], []),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        ProductCategory,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'filterProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBusinessProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BusinessProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersForManufacturer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getOrdersForProduct' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getOrdersForVendor' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductMessagesForProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductMessage)],
      ['query'],
    ),
  'getProductQuantities' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getProductQuantity' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsForManufacturer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BusinessProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isManufacturer' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isVendor' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([BusinessProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'seedData' : IDL.Func([], [], []),
  'sendProductMessage' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'setProductQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateBusinessProfile' : IDL.Func([BusinessProfile], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'manufacturer' : IDL.Null,
    'vendor' : IDL.Null,
  });
  const BusinessProfile = IDL.Record({
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'businessName' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const ProductCategory = IDL.Variant({
    'closure20Inch' : IDL.Null,
    'closure16Inch' : IDL.Null,
    'bundle12Inch' : IDL.Null,
    'curlyWig' : IDL.Null,
    'closure18Inch' : IDL.Null,
    'bundle14Inch' : IDL.Null,
    'bobWig' : IDL.Null,
    'bundle20Inch' : IDL.Null,
    'bundle16Inch' : IDL.Null,
    'closureWig' : IDL.Null,
    'bundle18Inch' : IDL.Null,
    'supplyBundle' : IDL.Null,
    'frontalWig' : IDL.Null,
    'blondeWig' : IDL.Null,
    'bodyWave' : IDL.Null,
    'closure12Inch' : IDL.Null,
    'deepWave' : IDL.Null,
    'closure14Inch' : IDL.Null,
    'boneStraight' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'moq' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'priceFromCents' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'lengthOptions' : IDL.Vec(IDL.Text),
    'manufacturerId' : IDL.Principal,
    'category' : ProductCategory,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'createdAt' : IDL.Int,
    'totalCents' : IDL.Nat,
    'productId' : IDL.Nat,
    'buyerId' : IDL.Principal,
    'quantity' : IDL.Nat,
    'sellerId' : IDL.Principal,
  });
  const ProductMessage = IDL.Record({
    'text' : IDL.Text,
    'productId' : IDL.Nat,
    'receiverId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'senderId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'completeOrder' : IDL.Func([IDL.Nat], [], []),
    'createBusinessProfile' : IDL.Func([BusinessProfile], [], []),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          ProductCategory,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'filterProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBusinessProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersForManufacturer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getOrdersForProduct' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getOrdersForVendor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductMessagesForProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductMessage)],
        ['query'],
      ),
    'getProductQuantities' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getProductQuantity' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsForManufacturer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isManufacturer' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isVendor' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([BusinessProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'seedData' : IDL.Func([], [], []),
    'sendProductMessage' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'setProductQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateBusinessProfile' : IDL.Func([BusinessProfile], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };