/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessProfile {
  'createdAt' : bigint,
  'role' : UserRole,
  'businessName' : string,
  'avatarUrl' : string,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'createdAt' : bigint,
  'totalCents' : bigint,
  'productId' : bigint,
  'buyerId' : Principal,
  'quantity' : bigint,
  'sellerId' : Principal,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export interface Product {
  'id' : bigint,
  'moq' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'lastUpdated' : bigint,
  'priceFromCents' : bigint,
  'imageUrl' : string,
  'lengthOptions' : Array<string>,
  'manufacturerId' : Principal,
  'category' : ProductCategory,
}
export type ProductCategory = { 'closure20Inch' : null } |
  { 'closure16Inch' : null } |
  { 'bundle12Inch' : null } |
  { 'curlyWig' : null } |
  { 'closure18Inch' : null } |
  { 'bundle14Inch' : null } |
  { 'bobWig' : null } |
  { 'bundle20Inch' : null } |
  { 'bundle16Inch' : null } |
  { 'closureWig' : null } |
  { 'bundle18Inch' : null } |
  { 'supplyBundle' : null } |
  { 'frontalWig' : null } |
  { 'blondeWig' : null } |
  { 'bodyWave' : null } |
  { 'closure12Inch' : null } |
  { 'deepWave' : null } |
  { 'closure14Inch' : null } |
  { 'boneStraight' : null };
export interface ProductMessage {
  'text' : string,
  'productId' : bigint,
  'receiverId' : Principal,
  'timestamp' : bigint,
  'senderId' : Principal,
}
export type UserRole = { 'manufacturer' : null } |
  { 'vendor' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'completeOrder' : ActorMethod<[bigint], undefined>,
  'createBusinessProfile' : ActorMethod<[BusinessProfile], undefined>,
  'createProduct' : ActorMethod<
    [string, ProductCategory, bigint, Array<string>, bigint, string],
    bigint
  >,
  'filterProducts' : ActorMethod<[string], Array<Product>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBusinessProfile' : ActorMethod<[Principal], [] | [BusinessProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [BusinessProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersForManufacturer' : ActorMethod<[Principal], Array<Order>>,
  'getOrdersForProduct' : ActorMethod<[bigint], Array<Order>>,
  'getOrdersForVendor' : ActorMethod<[Principal], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductMessagesForProduct' : ActorMethod<[bigint], Array<ProductMessage>>,
  'getProductQuantities' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getProductQuantity' : ActorMethod<[bigint], bigint>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getProductsForManufacturer' : ActorMethod<[Principal], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [BusinessProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isManufacturer' : ActorMethod<[Principal], boolean>,
  'isVendor' : ActorMethod<[Principal], boolean>,
  'placeOrder' : ActorMethod<[bigint, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[BusinessProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'seedData' : ActorMethod<[], undefined>,
  'sendProductMessage' : ActorMethod<[Principal, bigint, string], undefined>,
  'setProductQuantity' : ActorMethod<[bigint, bigint], undefined>,
  'updateBusinessProfile' : ActorMethod<[BusinessProfile], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, bigint, Array<string>, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];