/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductMessage {
    text: string;
    productId: bigint;
    receiverId: Principal;
    timestamp: bigint;
    senderId: Principal;
}
export interface BusinessProfile {
    createdAt: bigint;
    role: UserRole;
    businessName: string;
    avatarUrl: string;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    createdAt: bigint;
    totalCents: bigint;
    productId: bigint;
    buyerId: Principal;
    quantity: bigint;
    sellerId: Principal;
}
export interface Product {
    id: bigint;
    moq: bigint;
    name: string;
    createdAt: bigint;
    lastUpdated: bigint;
    priceFromCents: bigint;
    imageUrl: string;
    lengthOptions: Array<string>;
    manufacturerId: Principal;
    category: ProductCategory;
}
export enum OrderStatus {
    shipped = "shipped",
    pending = "pending",
    delivered = "delivered"
}
export enum ProductCategory {
    closure20Inch = "closure20Inch",
    closure16Inch = "closure16Inch",
    bundle12Inch = "bundle12Inch",
    curlyWig = "curlyWig",
    closure18Inch = "closure18Inch",
    bundle14Inch = "bundle14Inch",
    bobWig = "bobWig",
    bundle20Inch = "bundle20Inch",
    bundle16Inch = "bundle16Inch",
    closureWig = "closureWig",
    bundle18Inch = "bundle18Inch",
    supplyBundle = "supplyBundle",
    frontalWig = "frontalWig",
    blondeWig = "blondeWig",
    bodyWave = "bodyWave",
    closure12Inch = "closure12Inch",
    deepWave = "deepWave",
    closure14Inch = "closure14Inch",
    boneStraight = "boneStraight"
}
export enum UserRole {
    manufacturer = "manufacturer",
    vendor = "vendor"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    completeOrder(orderId: bigint): Promise<void>;
    createBusinessProfile(profile: BusinessProfile): Promise<void>;
    createProduct(name: string, category: ProductCategory, priceFromCents: bigint, lengthOptions: Array<string>, moq: bigint, imageUrl: string): Promise<bigint>;
    filterProducts(sort: string): Promise<Array<Product>>;
    getAllProducts(): Promise<Array<Product>>;
    getBusinessProfile(user: Principal): Promise<BusinessProfile | null>;
    getCallerUserProfile(): Promise<BusinessProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getOrder(orderId: bigint): Promise<Order | null>;
    getOrdersForManufacturer(manufacturerId: Principal): Promise<Array<Order>>;
    getOrdersForProduct(productId: bigint): Promise<Array<Order>>;
    getOrdersForVendor(vendorId: Principal): Promise<Array<Order>>;
    getProduct(productId: bigint): Promise<Product | null>;
    getProductMessagesForProduct(productId: bigint): Promise<Array<ProductMessage>>;
    getProductQuantities(): Promise<Array<[bigint, bigint]>>;
    getProductQuantity(productId: bigint): Promise<bigint>;
    getProductsByCategory(category: ProductCategory): Promise<Array<Product>>;
    getProductsForManufacturer(manufacturerId: Principal): Promise<Array<Product>>;
    getUserProfile(user: Principal): Promise<BusinessProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isManufacturer(profileId: Principal): Promise<boolean>;
    isVendor(profileId: Principal): Promise<boolean>;
    placeOrder(productId: bigint, quantity: bigint): Promise<bigint>;
    saveCallerUserProfile(profile: BusinessProfile): Promise<void>;
    searchProducts(searchTerm: string): Promise<Array<Product>>;
    seedData(): Promise<void>;
    sendProductMessage(receiverId: Principal, productId: bigint, text: string): Promise<void>;
    setProductQuantity(productId: bigint, quantity: bigint): Promise<void>;
    updateBusinessProfile(profile: BusinessProfile): Promise<void>;
    updateProduct(productId: bigint, name: string, priceFromCents: bigint, lengthOptions: Array<string>, moq: bigint, imageUrl: string): Promise<void>;
}
import type { BusinessProfile as _BusinessProfile, Order as _Order, OrderStatus as _OrderStatus, Product as _Product, ProductCategory as _ProductCategory, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeOrder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeOrder(arg0);
            return result;
        }
    }
    async createBusinessProfile(arg0: BusinessProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBusinessProfile(to_candid_BusinessProfile_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBusinessProfile(to_candid_BusinessProfile_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProduct(arg0: string, arg1: ProductCategory, arg2: bigint, arg3: Array<string>, arg4: bigint, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, to_candid_ProductCategory_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, to_candid_ProductCategory_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async filterProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterProducts(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterProducts(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusinessProfile(arg0: Principal): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersForManufacturer(arg0: Principal): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersForManufacturer(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersForManufacturer(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersForProduct(arg0: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersForProduct(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersForProduct(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersForVendor(arg0: Principal): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersForVendor(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersForVendor(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductMessagesForProduct(arg0: bigint): Promise<Array<ProductMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductMessagesForProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductMessagesForProduct(arg0);
            return result;
        }
    }
    async getProductQuantities(): Promise<Array<[bigint, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductQuantities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductQuantities();
            return result;
        }
    }
    async getProductQuantity(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductQuantity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductQuantity(arg0);
            return result;
        }
    }
    async getProductsByCategory(arg0: ProductCategory): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsForManufacturer(arg0: Principal): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsForManufacturer(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsForManufacturer(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isManufacturer(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isManufacturer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isManufacturer(arg0);
            return result;
        }
    }
    async isVendor(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isVendor(arg0);
            return result;
        }
    }
    async placeOrder(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: BusinessProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_BusinessProfile_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_BusinessProfile_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async sendProductMessage(arg0: Principal, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendProductMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendProductMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async setProductQuantity(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProductQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProductQuantity(arg0, arg1);
            return result;
        }
    }
    async updateBusinessProfile(arg0: BusinessProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBusinessProfile(to_candid_BusinessProfile_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBusinessProfile(to_candid_BusinessProfile_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: bigint, arg3: Array<string>, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_BusinessProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessProfile): BusinessProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusinessProfile]): BusinessProfile | null {
    return value.length === 0 ? null : from_candid_BusinessProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    moq: bigint;
    name: string;
    createdAt: bigint;
    lastUpdated: bigint;
    priceFromCents: bigint;
    imageUrl: string;
    lengthOptions: Array<string>;
    manufacturerId: Principal;
    category: _ProductCategory;
}): {
    id: bigint;
    moq: bigint;
    name: string;
    createdAt: bigint;
    lastUpdated: bigint;
    priceFromCents: bigint;
    imageUrl: string;
    lengthOptions: Array<string>;
    manufacturerId: Principal;
    category: ProductCategory;
} {
    return {
        id: value.id,
        moq: value.moq,
        name: value.name,
        createdAt: value.createdAt,
        lastUpdated: value.lastUpdated,
        priceFromCents: value.priceFromCents,
        imageUrl: value.imageUrl,
        lengthOptions: value.lengthOptions,
        manufacturerId: value.manufacturerId,
        category: from_candid_ProductCategory_n12(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: bigint;
    role: _UserRole;
    businessName: string;
    avatarUrl: string;
}): {
    createdAt: bigint;
    role: UserRole;
    businessName: string;
    avatarUrl: string;
} {
    return {
        createdAt: value.createdAt,
        role: from_candid_UserRole_n17(_uploadFile, _downloadFile, value.role),
        businessName: value.businessName,
        avatarUrl: value.avatarUrl
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    createdAt: bigint;
    totalCents: bigint;
    productId: bigint;
    buyerId: Principal;
    quantity: bigint;
    sellerId: Principal;
}): {
    id: bigint;
    status: OrderStatus;
    createdAt: bigint;
    totalCents: bigint;
    productId: bigint;
    buyerId: Principal;
    quantity: bigint;
    sellerId: Principal;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n24(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        totalCents: value.totalCents,
        productId: value.productId,
        buyerId: value.buyerId,
        quantity: value.quantity,
        sellerId: value.sellerId
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closure20Inch: null;
} | {
    closure16Inch: null;
} | {
    bundle12Inch: null;
} | {
    curlyWig: null;
} | {
    closure18Inch: null;
} | {
    bundle14Inch: null;
} | {
    bobWig: null;
} | {
    bundle20Inch: null;
} | {
    bundle16Inch: null;
} | {
    closureWig: null;
} | {
    bundle18Inch: null;
} | {
    supplyBundle: null;
} | {
    frontalWig: null;
} | {
    blondeWig: null;
} | {
    bodyWave: null;
} | {
    closure12Inch: null;
} | {
    deepWave: null;
} | {
    closure14Inch: null;
} | {
    boneStraight: null;
}): ProductCategory {
    return "closure20Inch" in value ? ProductCategory.closure20Inch : "closure16Inch" in value ? ProductCategory.closure16Inch : "bundle12Inch" in value ? ProductCategory.bundle12Inch : "curlyWig" in value ? ProductCategory.curlyWig : "closure18Inch" in value ? ProductCategory.closure18Inch : "bundle14Inch" in value ? ProductCategory.bundle14Inch : "bobWig" in value ? ProductCategory.bobWig : "bundle20Inch" in value ? ProductCategory.bundle20Inch : "bundle16Inch" in value ? ProductCategory.bundle16Inch : "closureWig" in value ? ProductCategory.closureWig : "bundle18Inch" in value ? ProductCategory.bundle18Inch : "supplyBundle" in value ? ProductCategory.supplyBundle : "frontalWig" in value ? ProductCategory.frontalWig : "blondeWig" in value ? ProductCategory.blondeWig : "bodyWave" in value ? ProductCategory.bodyWave : "closure12Inch" in value ? ProductCategory.closure12Inch : "deepWave" in value ? ProductCategory.deepWave : "closure14Inch" in value ? ProductCategory.closure14Inch : "boneStraight" in value ? ProductCategory.boneStraight : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manufacturer: null;
} | {
    vendor: null;
}): UserRole {
    return "manufacturer" in value ? UserRole.manufacturer : "vendor" in value ? UserRole.vendor : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    pending: null;
} | {
    delivered: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n10(_uploadFile, _downloadFile, x));
}
function to_candid_BusinessProfile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessProfile): _BusinessProfile {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: bigint;
    role: UserRole;
    businessName: string;
    avatarUrl: string;
}): {
    createdAt: bigint;
    role: _UserRole;
    businessName: string;
    avatarUrl: string;
} {
    return {
        createdAt: value.createdAt,
        role: to_candid_UserRole_n5(_uploadFile, _downloadFile, value.role),
        businessName: value.businessName,
        avatarUrl: value.avatarUrl
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    manufacturer: null;
} | {
    vendor: null;
} {
    return value == UserRole.manufacturer ? {
        manufacturer: null
    } : value == UserRole.vendor ? {
        vendor: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    closure20Inch: null;
} | {
    closure16Inch: null;
} | {
    bundle12Inch: null;
} | {
    curlyWig: null;
} | {
    closure18Inch: null;
} | {
    bundle14Inch: null;
} | {
    bobWig: null;
} | {
    bundle20Inch: null;
} | {
    bundle16Inch: null;
} | {
    closureWig: null;
} | {
    bundle18Inch: null;
} | {
    supplyBundle: null;
} | {
    frontalWig: null;
} | {
    blondeWig: null;
} | {
    bodyWave: null;
} | {
    closure12Inch: null;
} | {
    deepWave: null;
} | {
    closure14Inch: null;
} | {
    boneStraight: null;
} {
    return value == ProductCategory.closure20Inch ? {
        closure20Inch: null
    } : value == ProductCategory.closure16Inch ? {
        closure16Inch: null
    } : value == ProductCategory.bundle12Inch ? {
        bundle12Inch: null
    } : value == ProductCategory.curlyWig ? {
        curlyWig: null
    } : value == ProductCategory.closure18Inch ? {
        closure18Inch: null
    } : value == ProductCategory.bundle14Inch ? {
        bundle14Inch: null
    } : value == ProductCategory.bobWig ? {
        bobWig: null
    } : value == ProductCategory.bundle20Inch ? {
        bundle20Inch: null
    } : value == ProductCategory.bundle16Inch ? {
        bundle16Inch: null
    } : value == ProductCategory.closureWig ? {
        closureWig: null
    } : value == ProductCategory.bundle18Inch ? {
        bundle18Inch: null
    } : value == ProductCategory.supplyBundle ? {
        supplyBundle: null
    } : value == ProductCategory.frontalWig ? {
        frontalWig: null
    } : value == ProductCategory.blondeWig ? {
        blondeWig: null
    } : value == ProductCategory.bodyWave ? {
        bodyWave: null
    } : value == ProductCategory.closure12Inch ? {
        closure12Inch: null
    } : value == ProductCategory.deepWave ? {
        deepWave: null
    } : value == ProductCategory.closure14Inch ? {
        closure14Inch: null
    } : value == ProductCategory.boneStraight ? {
        boneStraight: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
